/**
 * 播放列表
 * @type {Array}
 * 请用数组来定义总列表
 * 再用二维数组定义每个列表
 * 其中列表里的每首歌需用对象定义
 * 请在每个列表中的第一个元素定义列表信息（必须位于第一位）
 * 列表信息必须有一个basic属性，值为true
 * 还要有一个name属性，值为列表名称
 * 可选参数为singer、image，用于为定义的该属性的歌曲调用
 * 每首歌必须有name、src、lrc三个属性
 * src为歌曲相对于index.html的相对路径或绝对路径
 * 可选singer和image属性
 * 在每首歌没有定义singer或image时将使用列表的singer或image
 * 请确保一定有一个被定义
 * 其中name为歌曲名称
 * src为歌曲文件路径
 * lrc为歌词，请用\n或\r将每行歌词隔开，否则无法识别
 */
var mplayer_song = [[
	{
		"basic":true,
		"name":"国语音乐",
		"singer":"流行",
		"img":"./img/fm1.jpg"
	},
{"name":"给我一个理由忘记","singer":"ALin","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/ALin-给我一个理由忘记.mp3","lrc":""},
{"name":"有一种悲伤","singer":"ALin","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/ALin-有一种悲伤.mp3","lrc":""},
{"name":"陪我去流浪","singer":"阿悄","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/阿悄-陪我去流浪.mp3","lrc":""},
{"name":"疯了","singer":"阿桑","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/阿桑-疯了.mp3","lrc":""},
{"name":"寂寞在唱歌","singer":"阿桑","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/阿桑-寂寞在唱歌.mp3","lrc":""},
{"name":"受了点伤","singer":"阿桑","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/阿桑-受了点伤.mp3","lrc":""},
{"name":"追光者","singer":"岑宁儿","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/岑宁儿-追光者.mp3","lrc":""},
{"name":"触电(爱的魔力转圈圈)","singer":"岑雨桥、萧全","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/岑雨桥、萧全-触电(爱的魔力转圈圈).mp3","lrc":""},
{"name":"就让你走","singer":"陈冠蒲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/陈冠蒲-就让你走.mp3","lrc":""},
{"name":"太多","singer":"陈冠蒲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/陈冠蒲-太多.mp3","lrc":""},
{"name":"千千阙歌","singer":"陈慧娴","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/陈慧娴-千千阙歌.mp3","lrc":""},
{"name":"爱就爱了","singer":"陈琳","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/陈琳-爱就爱了.mp3","lrc":""},
{"name":"等你爱我","singer":"陈明","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/陈明-等你爱我.mp3","lrc":""},
{"name":"我要找到你","singer":"陈明","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/陈明-我要找到你.mp3","lrc":""},
{"name":"白狐","singer":"陈瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/陈瑞-白狐.mp3","lrc":""},
{"name":"情关","singer":"陈淑桦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/陈淑桦-情关.mp3","lrc":""},
{"name":"野狼Disco","singer":"陈伟霆、宝石Gem","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/陈伟霆、宝石Gem-野狼Disco.mp3","lrc":""},
{"name":"无尽的爱","singer":"成龙、金喜善","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/成龙、金喜善-无尽的爱.mp3","lrc":""},
{"name":"我们不一样","singer":"大壮","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/大壮-我们不一样.mp3","lrc":""},
{"name":"爱疯了","singer":"戴佩妮","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/戴佩妮-爱疯了.mp3","lrc":""},
{"name":"街角的祝福","singer":"戴佩妮","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/戴佩妮-街角的祝福.mp3","lrc":""},
{"name":"你要的爱","singer":"戴佩妮","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/戴佩妮-你要的爱.mp3","lrc":""},
{"name":"怎样","singer":"戴佩妮","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/戴佩妮-怎样.mp3","lrc":""},
{"name":"倒数","singer":"邓紫棋","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/邓紫棋-倒数.mp3","lrc":""},
{"name":"光年之外","singer":"邓紫棋","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/邓紫棋-光年之外.mp3","lrc":""},
{"name":"你把我灌醉","singer":"邓紫棋","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/邓紫棋-你把我灌醉.mp3","lrc":""},
{"name":"泡沫","singer":"邓紫棋","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/邓紫棋-泡沫.mp3","lrc":""},
{"name":"偏偏","singer":"迪丽热巴、汪苏泷","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/迪丽热巴、汪苏泷-偏偏.mp3","lrc":""},
{"name":"知心爱人","singer":"付笛声、任静","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/付笛声、任静-知心爱人.mp3","lrc":""},
{"name":"渡情","singer":"高胜美、左宏元","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/高胜美、左宏元-渡情.mp3","lrc":""},
{"name":"第一次","singer":"光良","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/光良-第一次.mp3","lrc":""},
{"name":"都是你","singer":"光良","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/光良-都是你.mp3","lrc":""},
{"name":"童话","singer":"光良","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/光良-童话.mp3","lrc":""},
{"name":"飘雪","singer":"韩雪","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/韩雪-飘雪.mp3","lrc":""},
{"name":"想起","singer":"韩雪","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/韩雪-想起.mp3","lrc":""},
{"name":"无地自容","singer":"黑豹乐队","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/黑豹乐队-无地自容.mp3","lrc":""},
{"name":"知否知否","singer":"胡夏、郁可唯","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/胡夏、郁可唯-知否知否.mp3","lrc":""},
{"name":"伴","singer":"黄小琥","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/黄小琥-伴.mp3","lrc":""},
{"name":"没那么简单","singer":"黄小琥","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/黄小琥-没那么简单.mp3","lrc":""},
{"name":"顺其自然","singer":"黄小琥","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/黄小琥-顺其自然.mp3","lrc":""},
{"name":"重来","singer":"黄小琥","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/黄小琥-重来.mp3","lrc":""},
{"name":"卡路里","singer":"火箭少女101","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/火箭少女101-卡路里.mp3","lrc":""},
{"name":"梅花三弄","singer":"姜育恒","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/姜育恒-梅花三弄.mp3","lrc":""},
{"name":"贝加尔湖畔","singer":"李健","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/李健-贝加尔湖畔.mp3","lrc":""},
{"name":"当你老了(Live)","singer":"李健","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/李健-当你老了(Live).mp3","lrc":""},
{"name":"风吹麦浪","singer":"李健","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/李健-风吹麦浪.mp3","lrc":""},
{"name":"想你的365天","singer":"李玟","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/李玟-想你的365天.mp3","lrc":""},
{"name":"月光爱人","singer":"李玟","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/李玟-月光爱人.mp3","lrc":""},
{"name":"小偷","singer":"李沁","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/李沁-小偷.mp3","lrc":""},
{"name":"麻雀","singer":"李荣浩","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/李荣浩-麻雀.mp3","lrc":""},
{"name":"模特","singer":"李荣浩","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/李荣浩-模特.mp3","lrc":""},
{"name":"年少有为","singer":"李荣浩","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/李荣浩-年少有为.mp3","lrc":""},
{"name":"痴心绝对","singer":"李圣杰","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/李圣杰-痴心绝对.mp3","lrc":""},
{"name":"手放开","singer":"李圣杰","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/李圣杰-手放开.mp3","lrc":""},
{"name":"你笑起来真好看","singer":"李昕融、樊桐舟、李凯稠","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/李昕融、樊桐舟、李凯稠-你笑起来真好看.mp3","lrc":""},
{"name":"梨花香","singer":"李宇春","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/李宇春-梨花香.mp3","lrc":""},
{"name":"无价之姐","singer":"李宇春","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/李宇春-无价之姐.mp3","lrc":""},
{"name":"爱你不是两三天","singer":"梁静茹","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/梁静茹-爱你不是两三天.mp3","lrc":""},
{"name":"可惜不是你","singer":"梁静茹","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/梁静茹-可惜不是你.mp3","lrc":""},
{"name":"勇气","singer":"梁静茹","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/梁静茹-勇气.mp3","lrc":""},
{"name":"江南","singer":"林俊杰","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/林俊杰-江南.mp3","lrc":""},
{"name":"一千年以后","singer":"林俊杰","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/林俊杰-一千年以后.mp3","lrc":""},
{"name":"醉赤壁","singer":"林俊杰","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/林俊杰-醉赤壁.mp3","lrc":""},
{"name":"落花","singer":"林心如","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/林心如-落花.mp3","lrc":""},
{"name":"倾听我","singer":"林心如","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/林心如-倾听我.mp3","lrc":""},
{"name":"不必在乎我是谁","singer":"林忆莲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/林忆莲-不必在乎我是谁.mp3","lrc":""},
{"name":"伤痕","singer":"林忆莲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/林忆莲-伤痕.mp3","lrc":""},
{"name":"至少还有你","singer":"林忆莲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/林忆莲-至少还有你.mp3","lrc":""},
{"name":"没离开过","singer":"林志炫","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/林志炫-没离开过.mp3","lrc":""},
{"name":"烟花易冷","singer":"林志炫","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/林志炫-烟花易冷.mp3","lrc":""},
{"name":"相信自己","singer":"零点乐队","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/零点乐队-相信自己.mp3","lrc":""},
{"name":"冰雨","singer":"刘德华","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/刘德华-冰雨.mp3","lrc":""},
{"name":"芙蓉雨","singer":"刘珂矣","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/刘珂矣-芙蓉雨.mp3","lrc":""},
{"name":"很爱很爱你","singer":"刘若英","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/刘若英-很爱很爱你.mp3","lrc":""},
{"name":"后来","singer":"刘若英","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/刘若英-后来.mp3","lrc":""},
{"name":"为爱痴狂","singer":"刘若英","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/刘若英-为爱痴狂.mp3","lrc":""},
{"name":"一辈子的孤单","singer":"刘若英","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/刘若英-一辈子的孤单.mp3","lrc":""},
{"name":"一生所爱","singer":"卢冠廷","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/卢冠廷-一生所爱.mp3","lrc":""},
{"name":"铁血丹心","singer":"罗文、甄妮","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/罗文、甄妮-铁血丹心.mp3","lrc":""},
{"name":"懂你","singer":"满文军","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/满文军-懂你.mp3","lrc":""},
{"name":"少年","singer":"梦然","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/梦然-少年.mp3","lrc":""},
{"name":"电台情歌","singer":"莫文蔚","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/莫文蔚-电台情歌.mp3","lrc":""},
{"name":"盛夏的果实","singer":"莫文蔚","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/莫文蔚-盛夏的果实.mp3","lrc":""},
{"name":"不得不爱","singer":"潘玮柏","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/潘玮柏-不得不爱.mp3","lrc":""},
{"name":"快乐崇拜","singer":"潘玮柏","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/潘玮柏-快乐崇拜.mp3","lrc":""},
{"name":"天天天蓝","singer":"潘越云","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/潘越云-天天天蓝.mp3","lrc":""},
{"name":"我是不是你最疼爱的人","singer":"潘越云","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/潘越云-我是不是你最疼爱的人.mp3","lrc":""},
{"name":"不让我的眼泪陪我过夜","singer":"齐秦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/齐秦-不让我的眼泪陪我过夜.mp3","lrc":""},
{"name":"大约在冬季","singer":"齐秦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/齐秦-大约在冬季.mp3","lrc":""},
{"name":"往事随风","singer":"齐秦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/齐秦-往事随风.mp3","lrc":""},
{"name":"无情的雨无情的你","singer":"齐秦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/齐秦-无情的雨无情的你.mp3","lrc":""},
{"name":"夜夜夜夜","singer":"齐秦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/齐秦-夜夜夜夜.mp3","lrc":""},
{"name":"橄榄树","singer":"齐豫","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/齐豫-橄榄树.mp3","lrc":""},
{"name":"十一年","singer":"邱永传","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/邱永传-十一年.mp3","lrc":""},
{"name":"爱我的人和我爱的人","singer":"裘海正","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/裘海正-爱我的人和我爱的人.mp3","lrc":""},
{"name":"九千九百九十九滴眼泪","singer":"裘海正","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/裘海正-九千九百九十九滴眼泪.mp3","lrc":""},
{"name":"小雪","singer":"任贤齐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/任贤齐-小雪.mp3","lrc":""},
{"name":"心太软","singer":"任贤齐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/任贤齐-心太软.mp3","lrc":""},
{"name":"小小","singer":"容祖儿","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/容祖儿-小小.mp3","lrc":""},
{"name":"暗香","singer":"沙宝亮","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/沙宝亮-暗香.mp3","lrc":""},
{"name":"斑马斑马","singer":"沙宝亮","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/沙宝亮-斑马斑马.mp3","lrc":""},
{"name":"牵手","singer":"苏芮","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/苏芮-牵手.mp3","lrc":""},
{"name":"天黑黑","singer":"孙燕姿","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/孙燕姿-天黑黑.mp3","lrc":""},
{"name":"我要的幸福","singer":"孙燕姿","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/孙燕姿-我要的幸福.mp3","lrc":""},
{"name":"遇见","singer":"孙燕姿","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/孙燕姿-遇见.mp3","lrc":""},
{"name":"原来你什么都不要","singer":"孙燕姿","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/孙燕姿-原来你什么都不要.mp3","lrc":""},
{"name":"心情不错","singer":"孙悦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/孙悦-心情不错.mp3","lrc":""},
{"name":"好人好梦","singer":"邰正宵、孙悦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/邰正宵、孙悦-好人好梦.mp3","lrc":""},
{"name":"九百九十九朵玫瑰","singer":"邰正宵","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/邰正宵-九百九十九朵玫瑰.mp3","lrc":""},
{"name":"千纸鹤","singer":"邰正宵","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/邰正宵-千纸鹤.mp3","lrc":""},
{"name":"心要让你听见","singer":"邰正宵","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/邰正宵-心要让你听见.mp3","lrc":""},
{"name":"一千零一夜","singer":"邰正宵","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/邰正宵-一千零一夜.mp3","lrc":""},
{"name":"找一个字代替","singer":"邰正宵","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/邰正宵-找一个字代替.mp3","lrc":""},
{"name":"小幸运","singer":"田馥甄","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/田馥甄-小幸运.mp3","lrc":""},
{"name":"北京北京","singer":"汪峰","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/汪峰-北京北京.mp3","lrc":""},
{"name":"存在","singer":"汪峰","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/汪峰-存在.mp3","lrc":""},
{"name":"怒放的生命","singer":"汪峰","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/汪峰-怒放的生命.mp3","lrc":""},
{"name":"超越梦想","singer":"汪正正","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/汪正正-超越梦想.mp3","lrc":""},
{"name":"重头再来","singer":"汪正正","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/汪正正-重头再来.mp3","lrc":""},
{"name":"传奇","singer":"王菲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/王菲-传奇.mp3","lrc":""},
{"name":"伤心1999","singer":"王杰","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/王杰-伤心1999.mp3","lrc":""},
{"name":"忘记你不如忘记自己","singer":"王杰","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/王杰-忘记你不如忘记自己.mp3","lrc":""},
{"name":"忘了你忘了我","singer":"王杰","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/王杰-忘了你忘了我.mp3","lrc":""},
{"name":"为了爱梦一生","singer":"王杰","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/王杰-为了爱梦一生.mp3","lrc":""},
{"name":"一场游戏一场梦","singer":"王杰","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/王杰-一场游戏一场梦.mp3","lrc":""},
{"name":"一无所有","singer":"王杰","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/王杰-一无所有.mp3","lrc":""},
{"name":"爱的就是你","singer":"王力宏","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/王力宏-爱的就是你.mp3","lrc":""},
{"name":"唯一","singer":"王力宏","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/王力宏-唯一.mp3","lrc":""},
{"name":"时间都去哪儿了","singer":"王铮亮","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/王铮亮-时间都去哪儿了.mp3","lrc":""},
{"name":"偷走","singer":"萧煌奇","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/萧煌奇-偷走.mp3","lrc":""},
{"name":"Cappuccino","singer":"萧亚轩","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/萧亚轩-Cappuccino.mp3","lrc":""},
{"name":"HoneyHoneyHoney","singer":"萧亚轩","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/萧亚轩-HoneyHoneyHoney.mp3","lrc":""},
{"name":"窗外的天气","singer":"萧亚轩","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/萧亚轩-窗外的天气.mp3","lrc":""},
{"name":"突然想起你","singer":"萧亚轩","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/萧亚轩-突然想起你.mp3","lrc":""},
{"name":"我爱你那么多","singer":"萧亚轩","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/萧亚轩-我爱你那么多.mp3","lrc":""},
{"name":"一个人的精彩","singer":"萧亚轩","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/萧亚轩-一个人的精彩.mp3","lrc":""},
{"name":"最熟悉的陌生人","singer":"萧亚轩","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/萧亚轩-最熟悉的陌生人.mp3","lrc":""},
{"name":"学猫叫","singer":"小潘潘、小峰峰","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/小潘潘、小峰峰-学猫叫.mp3","lrc":""},
{"name":"味道","singer":"辛晓琪","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/辛晓琪-味道.mp3","lrc":""},
{"name":"海阔天空","singer":"信乐团","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/信乐团-海阔天空.mp3","lrc":""},
{"name":"假如","singer":"信乐团","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/信乐团-假如.mp3","lrc":""},
{"name":"离歌","singer":"信乐团","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/信乐团-离歌.mp3","lrc":""},
{"name":"死了都要爱","singer":"信乐团","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/信乐团-死了都要爱.mp3","lrc":""},
{"name":"突然好想你","singer":"徐佳莹","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/徐佳莹-突然好想你.mp3","lrc":""},
{"name":"七月七日晴","singer":"许慧欣","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许慧欣-七月七日晴.mp3","lrc":""},
{"name":"预谋","singer":"许佳慧","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许佳慧-预谋.mp3","lrc":""},
{"name":"荡漾","singer":"许美静","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许美静-荡漾.mp3","lrc":""},
{"name":"都是夜归人","singer":"许美静","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许美静-都是夜归人.mp3","lrc":""},
{"name":"快乐无罪","singer":"许美静","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许美静-快乐无罪.mp3","lrc":""},
{"name":"蔓延","singer":"许美静","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许美静-蔓延.mp3","lrc":""},
{"name":"迷乱","singer":"许美静","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许美静-迷乱.mp3","lrc":""},
{"name":"迫在眉梢","singer":"许美静","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许美静-迫在眉梢.mp3","lrc":""},
{"name":"铁窗","singer":"许美静","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许美静-铁窗.mp3","lrc":""},
{"name":"阳光总在风雨后","singer":"许美静","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许美静-阳光总在风雨后.mp3","lrc":""},
{"name":"遗憾","singer":"许美静","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许美静-遗憾.mp3","lrc":""},
{"name":"独角戏","singer":"许茹芸","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许茹芸-独角戏.mp3","lrc":""},
{"name":"泪海","singer":"许茹芸","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许茹芸-泪海.mp3","lrc":""},
{"name":"日光机场","singer":"许茹芸","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许茹芸-日光机场.mp3","lrc":""},
{"name":"如果云知道","singer":"许茹芸","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许茹芸-如果云知道.mp3","lrc":""},
{"name":"一直是晴天","singer":"许茹芸","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许茹芸-一直是晴天.mp3","lrc":""},
{"name":"花香","singer":"许韶洋","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许韶洋-花香.mp3","lrc":""},
{"name":"幸福的瞬间","singer":"许韶洋","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许韶洋-幸福的瞬间.mp3","lrc":""},
{"name":"曾经的你","singer":"许巍","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/许巍-曾经的你.mp3","lrc":""},
{"name":"暧昧","singer":"薛之谦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/薛之谦-暧昧.mp3","lrc":""},
{"name":"丑八怪","singer":"薛之谦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/薛之谦-丑八怪.mp3","lrc":""},
{"name":"你还要我怎样","singer":"薛之谦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/薛之谦-你还要我怎样.mp3","lrc":""},
{"name":"演员","singer":"薛之谦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/薛之谦-演员.mp3","lrc":""},
{"name":"三寸天堂","singer":"严艺丹","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/严艺丹-三寸天堂.mp3","lrc":""},
{"name":"凉凉","singer":"杨宗纬 张碧晨","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/杨宗纬 张碧晨-凉凉.mp3","lrc":""},
{"name":"上海滩","singer":"叶丽仪","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/叶丽仪-上海滩.mp3","lrc":""},
{"name":"选择","singer":"叶倩文、林子祥","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/叶倩文、林子祥-选择.mp3","lrc":""},
{"name":"真心真意过一生","singer":"叶倩文","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/叶倩文-真心真意过一生.mp3","lrc":""},
{"name":"体面","singer":"于文文","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/于文文-体面.mp3","lrc":""},
{"name":"红豆红","singer":"俞静","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/俞静-红豆红.mp3","lrc":""},
{"name":"感觉不到你","singer":"羽·泉","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/羽·泉-感觉不到你.mp3","lrc":""},
{"name":"冷酷到底","singer":"羽·泉","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/羽·泉-冷酷到底.mp3","lrc":""},
{"name":"深呼吸","singer":"羽·泉","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/羽·泉-深呼吸.mp3","lrc":""},
{"name":"最美","singer":"羽·泉","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/羽·泉-最美.mp3","lrc":""},
{"name":"情非得已","singer":"庾澄庆","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/庾澄庆-情非得已.mp3","lrc":""},
{"name":"时间煮雨","singer":"郁可唯","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/郁可唯-时间煮雨.mp3","lrc":""},
{"name":"思慕","singer":"郁可唯","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/郁可唯-思慕.mp3","lrc":""},
{"name":"说散就散","singer":"袁娅维","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/袁娅维-说散就散.mp3","lrc":""},
{"name":"年轮","singer":"张碧晨","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张碧晨-年轮.mp3","lrc":""},
{"name":"剪爱","singer":"张惠妹","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张惠妹-剪爱.mp3","lrc":""},
{"name":"哭不出来","singer":"张惠妹","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张惠妹-哭不出来.mp3","lrc":""},
{"name":"听海","singer":"张惠妹","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张惠妹-听海.mp3","lrc":""},
{"name":"站在高岗上","singer":"张惠妹","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张惠妹-站在高岗上.mp3","lrc":""},
{"name":"画心","singer":"张靓颖","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张靓颖-画心.mp3","lrc":""},
{"name":"呐喊","singer":"张韶涵","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张韶涵-呐喊.mp3","lrc":""},
{"name":"欧若拉","singer":"张韶涵","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张韶涵-欧若拉.mp3","lrc":""},
{"name":"隐形的翅膀","singer":"张韶涵","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张韶涵-隐形的翅膀.mp3","lrc":""},
{"name":"寓言","singer":"张韶涵","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张韶涵-寓言.mp3","lrc":""},
{"name":"孤独不苦","singer":"张卫健","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张卫健-孤独不苦.mp3","lrc":""},
{"name":"虚虚实实","singer":"张卫健","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张卫健-虚虚实实.mp3","lrc":""},
{"name":"一辈子一场梦","singer":"张卫健","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张卫健-一辈子一场梦.mp3","lrc":""},
{"name":"别让情两难","singer":"张信哲、范文芳","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张信哲、范文芳-别让情两难.mp3","lrc":""},
{"name":"有一点动心","singer":"张信哲、刘嘉玲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张信哲、刘嘉玲-有一点动心.mp3","lrc":""},
{"name":"爱不留","singer":"张信哲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张信哲-爱不留.mp3","lrc":""},
{"name":"爱就一个字","singer":"张信哲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张信哲-爱就一个字.mp3","lrc":""},
{"name":"爱如潮水","singer":"张信哲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张信哲-爱如潮水.mp3","lrc":""},
{"name":"别怕我伤心","singer":"张信哲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张信哲-别怕我伤心.mp3","lrc":""},
{"name":"不要对他说","singer":"张信哲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张信哲-不要对他说.mp3","lrc":""},
{"name":"从开始到现在","singer":"张信哲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张信哲-从开始到现在.mp3","lrc":""},
{"name":"过火","singer":"张信哲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张信哲-过火.mp3","lrc":""},
{"name":"宽容","singer":"张信哲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张信哲-宽容.mp3","lrc":""},
{"name":"某某某","singer":"张信哲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张信哲-某某某.mp3","lrc":""},
{"name":"难以抗拒你容颜","singer":"张信哲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张信哲-难以抗拒你容颜.mp3","lrc":""},
{"name":"太想爱你","singer":"张信哲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张信哲-太想爱你.mp3","lrc":""},
{"name":"信仰","singer":"张信哲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张信哲-信仰.mp3","lrc":""},
{"name":"用情","singer":"张信哲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张信哲-用情.mp3","lrc":""},
{"name":"直觉","singer":"张信哲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张信哲-直觉.mp3","lrc":""},
{"name":"当我想起你","singer":"张学友","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张学友-当我想起你.mp3","lrc":""},
{"name":"分手总要在雨天","singer":"张学友","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张学友-分手总要在雨天.mp3","lrc":""},
{"name":"情书","singer":"张学友","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张学友-情书.mp3","lrc":""},
{"name":"秋意浓","singer":"张学友","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张学友-秋意浓.mp3","lrc":""},
{"name":"吻别","singer":"张学友","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张学友-吻别.mp3","lrc":""},
{"name":"心如刀割","singer":"张学友","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张学友-心如刀割.mp3","lrc":""},
{"name":"一千个伤心的理由","singer":"张学友","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张学友-一千个伤心的理由.mp3","lrc":""},
{"name":"一言难尽","singer":"张宇","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张宇-一言难尽.mp3","lrc":""},
{"name":"雨一直下","singer":"张宇","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张宇-雨一直下.mp3","lrc":""},
{"name":"大海","singer":"张雨生","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张雨生-大海.mp3","lrc":""},
{"name":"探清水河","singer":"张云雷","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/张云雷-探清水河.mp3","lrc":""},
{"name":"闭月","singer":"赵方婧","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/赵方婧-闭月.mp3","lrc":""},
{"name":"尽头","singer":"赵方婧","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/赵方婧-尽头.mp3","lrc":""},
{"name":"芒种","singer":"赵方婧","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/赵方婧-芒种.mp3","lrc":""},
{"name":"青灯","singer":"赵方婧","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/赵方婧-青灯.mp3","lrc":""},
{"name":"瑞鹤仙","singer":"赵方婧","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/赵方婧-瑞鹤仙.mp3","lrc":""},
{"name":"小暑","singer":"赵方婧","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/赵方婧-小暑.mp3","lrc":""},
{"name":"直觉","singer":"赵方婧","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/赵方婧-直觉.mp3","lrc":""},
{"name":"成都","singer":"赵雷","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/赵雷-成都.mp3","lrc":""},
{"name":"时光话","singer":"赵露思","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/赵露思-时光话.mp3","lrc":""},
{"name":"笔记","singer":"周笔畅","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周笔畅-笔记.mp3","lrc":""},
{"name":"黄昏","singer":"周传雄","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周传雄-黄昏.mp3","lrc":""},
{"name":"风雨无阻","singer":"周华健","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周华健-风雨无阻.mp3","lrc":""},
{"name":"难念的经","singer":"周华健","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周华健-难念的经.mp3","lrc":""},
{"name":"不想让你知道","singer":"周蕙","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周蕙-不想让你知道.mp3","lrc":""},
{"name":"风铃","singer":"周蕙","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周蕙-风铃.mp3","lrc":""},
{"name":"好想好好爱你","singer":"周蕙","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周蕙-好想好好爱你.mp3","lrc":""},
{"name":"没有你","singer":"周蕙","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周蕙-没有你.mp3","lrc":""},
{"name":"我看","singer":"周蕙","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周蕙-我看.mp3","lrc":""},
{"name":"相遇太早","singer":"周蕙","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周蕙-相遇太早.mp3","lrc":""},
{"name":"约定","singer":"周蕙","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周蕙-约定.mp3","lrc":""},
{"name":"稻香","singer":"周杰伦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周杰伦-稻香.mp3","lrc":""},
{"name":"告白气球","singer":"周杰伦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周杰伦-告白气球.mp3","lrc":""},
{"name":"菊花台","singer":"周杰伦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周杰伦-菊花台.mp3","lrc":""},
{"name":"青花瓷","singer":"周杰伦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周杰伦-青花瓷.mp3","lrc":""},
{"name":"触不可及","singer":"周深","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周深-触不可及.mp3","lrc":""},
{"name":"此生惟你","singer":"周深","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周深-此生惟你.mp3","lrc":""},
{"name":"大鱼","singer":"周深","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周深-大鱼.mp3","lrc":""},
{"name":"欢颜","singer":"周深","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周深-欢颜.mp3","lrc":""},
{"name":"年轮(Live)","singer":"周深","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周深-年轮(Live).mp3","lrc":""},
{"name":"水形物语","singer":"周深","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周深-水形物语.mp3","lrc":""},
{"name":"微光海洋","singer":"周深","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周深-微光海洋.mp3","lrc":""},
{"name":"雪落下的声音(Live)","singer":"周深","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周深-雪落下的声音(Live).mp3","lrc":""},
{"name":"与卿","singer":"周深","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周深-与卿.mp3","lrc":""},
{"name":"愿得一心人","singer":"周深","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周深-愿得一心人.mp3","lrc":""},
{"name":"飘摇","singer":"周迅","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/周迅-飘摇.mp3","lrc":""},
{"name":"一万个舍不得","singer":"庄心妍、祁隆","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/庄心妍、祁隆-一万个舍不得.mp3","lrc":""},
{"name":"爱囚","singer":"庄心妍","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/庄心妍-爱囚.mp3","lrc":""},
{"name":"以后的以后","singer":"庄心妍","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/庄心妍-以后的以后.mp3","lrc":""},
{"name":"再见只是陌生人","singer":"庄心妍","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/庄心妍-再见只是陌生人.mp3","lrc":""},
{"name":"走着走着就散了","singer":"庄心妍","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/国语/庄心妍-走着走着就散了.mp3","lrc":""},
],
[
	{
		"basic":true,
		"name":"纯音乐",
		"singer":"纯音乐",
		"img":"./img/fm1.jpg"
	},
{"name":"爱在四月雪","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-爱在四月雪.mp3","lrc":""},
{"name":"安魂曲","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-安魂曲.mp3","lrc":""},
{"name":"安妮的歌","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-安妮的歌.mp3","lrc":""},
{"name":"宝贝珍之歌","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-宝贝珍之歌.mp3","lrc":""},
{"name":"沉睡的森林","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-沉睡的森林.mp3","lrc":""},
{"name":"沉思曲","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-沉思曲.mp3","lrc":""},
{"name":"初恋的地方","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-初恋的地方.mp3","lrc":""},
{"name":"春之声圆舞曲 古典钢琴","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-春之声圆舞曲 古典钢琴.mp3","lrc":""},
{"name":"大溪地清流 米奴哀舞","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-大溪地清流 米奴哀舞.mp3","lrc":""},
{"name":"第六感生死恋","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-第六感生死恋.mp3","lrc":""},
{"name":"断情殇","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-断情殇.mp3","lrc":""},
{"name":"飞鼠溪","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-飞鼠溪.mp3","lrc":""},
{"name":"风的气息","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-风的气息.mp3","lrc":""},
{"name":"风中之尘","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-风中之尘.mp3","lrc":""},
{"name":"格里格索尔维格之歌","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-格里格索尔维格之歌.mp3","lrc":""},
{"name":"和兰花在一起","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-和兰花在一起.mp3","lrc":""},
{"name":"很好听","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-很好听.mp3","lrc":""},
{"name":"火宵之月","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-火宵之月.mp3","lrc":""},
{"name":"卡布里的月光","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-卡布里的月光.mp3","lrc":""},
{"name":"卡农钢琴曲","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-卡农钢琴曲.mp3","lrc":""},
{"name":"蓝色的爱","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-蓝色的爱.mp3","lrc":""},
{"name":"梁祝之化蝶 笛子","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-梁祝之化蝶 笛子.mp3","lrc":""},
{"name":"绵雪","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-绵雪.mp3","lrc":""},
{"name":"茉莉花","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-茉莉花.mp3","lrc":""},
{"name":"森林中的一天","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-森林中的一天.mp3","lrc":""},
{"name":"似曾相识","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-似曾相识.mp3","lrc":""},
{"name":"守护你的天使","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-守护你的天使.mp3","lrc":""},
{"name":"树蛙之歌","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-树蛙之歌.mp3","lrc":""},
{"name":"水之轮回","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-水之轮回.mp3","lrc":""},
{"name":"天鹅湖","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-天鹅湖.mp3","lrc":""},
{"name":"万福玛丽亚","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-万福玛丽亚.mp3","lrc":""},
{"name":"我的海洋","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-我的海洋.mp3","lrc":""},
{"name":"西班牙斗牛士进行曲","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-西班牙斗牛士进行曲.mp3","lrc":""},
{"name":"西藏的月","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-西藏的月.mp3","lrc":""},
{"name":"昔日情怀","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-昔日情怀.mp3","lrc":""},
{"name":"夏日华尔兹","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-夏日华尔兹.mp3","lrc":""},
{"name":"乡间晚风","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-乡间晚风.mp3","lrc":""},
{"name":"相识也是缘份","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-相识也是缘份.mp3","lrc":""},
{"name":"小步舞曲","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-小步舞曲.mp3","lrc":""},
{"name":"小雨落在你脸上","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-小雨落在你脸上.mp3","lrc":""},
{"name":"雪之梦","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-雪之梦.mp3","lrc":""},
{"name":"野鸟情歌","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-野鸟情歌.mp3","lrc":""},
{"name":"印象之旅","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-印象之旅.mp3","lrc":""},
{"name":"雨林深处","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-雨林深处.mp3","lrc":""},
{"name":"雨中漫步","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-雨中漫步.mp3","lrc":""},
{"name":"月光下的凤尾竹","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-月光下的凤尾竹.mp3","lrc":""},
{"name":"云淡风轻","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-云淡风轻.mp3","lrc":""},
{"name":"只此一生","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-只此一生.mp3","lrc":""},
{"name":"最终幻想","singer":"纯音乐","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Chunyy-最终幻想.mp3","lrc":""},
{"name":"The level plain","singer":"Joanie madden","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/Joanie madden-The level plain.mp3","lrc":""},
{"name":"雨的印记","singer":"yiruma","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/yiruma-雨的印记.mp3","lrc":""},
{"name":"","singer":"爱尔兰风笛 漫步神秘园.mp3","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/爱尔兰风笛 漫步神秘园.mp3","lrc":""},
{"name":"爱尔兰画眉","singer":"爱尔兰口哨女皇madden","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/爱尔兰口哨女皇madden-爱尔兰画眉.mp3","lrc":""},
{"name":"chariots of fire","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-chariots of fire.mp3","lrc":""},
{"name":"diamonds","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-diamonds.mp3","lrc":""},
{"name":"EI condor pasa","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-EI condor pasa.mp3","lrc":""},
{"name":"i want to know love is","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-i want to know love is.mp3","lrc":""},
{"name":"i_swear","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-i_swear.mp3","lrc":""},
{"name":"imagine","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-imagine.mp3","lrc":""},
{"name":"into red velvet","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-into red velvet.mp3","lrc":""},
{"name":"moment of fantasy","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-moment of fantasy.mp3","lrc":""},
{"name":"one moment in time","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-one moment in time.mp3","lrc":""},
{"name":"tenderness","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-tenderness.mp3","lrc":""},
{"name":"the sounds of silence","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-the sounds of silence.mp3","lrc":""},
{"name":"tim's lullaby","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-tim's lullaby.mp3","lrc":""},
{"name":"安妮的仙境","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-安妮的仙境.mp3","lrc":""},
{"name":"变幻之风","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-变幻之风.mp3","lrc":""},
{"name":"晨光","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-晨光.mp3","lrc":""},
{"name":"初雪","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-初雪.mp3","lrc":""},
{"name":"春水","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-春水.mp3","lrc":""},
{"name":"春野","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-春野.mp3","lrc":""},
{"name":"非洲日落","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-非洲日落.mp3","lrc":""},
{"name":"风的呢喃","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-风的呢喃.mp3","lrc":""},
{"name":"海王星","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-海王星.mp3","lrc":""},
{"name":"火战车","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-火战车.mp3","lrc":""},
{"name":"涟漪","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-涟漪.mp3","lrc":""},
{"name":"马可波罗","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-马可波罗.mp3","lrc":""},
{"name":"满天星","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-满天星.mp3","lrc":""},
{"name":"秘密","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-秘密.mp3","lrc":""},
{"name":"排箫 老鹰之歌","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-排箫 老鹰之歌.mp3","lrc":""},
{"name":"清晨","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-清晨.mp3","lrc":""},
{"name":"日光海岸","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-日光海岸.mp3","lrc":""},
{"name":"天堂之门","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-天堂之门.mp3","lrc":""},
{"name":"微风山谷","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-微风山谷.mp3","lrc":""},
{"name":"无止境的见识","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-无止境的见识.mp3","lrc":""},
{"name":"夏日华尔兹","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-夏日华尔兹.mp3","lrc":""},
{"name":"仙境","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-仙境.mp3","lrc":""},
{"name":"依卡路斯的羽翼","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-依卡路斯的羽翼.mp3","lrc":""},
{"name":"忧郁的爱","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-忧郁的爱.mp3","lrc":""},
{"name":"月光 ","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-月光 .mp3","lrc":""},
{"name":"月光","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-月光.mp3","lrc":""},
{"name":"追梦人","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-追梦人.mp3","lrc":""},
{"name":"紫蝴蝶","singer":"班得瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班得瑞-紫蝴蝶.mp3","lrc":""},
{"name":"巴格达的星星","singer":"班德瑞","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/班德瑞-巴格达的星星.mp3","lrc":""},
{"name":"悲怆奏鸣曲","singer":"贝多芬","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/贝多芬-悲怆奏鸣曲.mp3","lrc":""},
{"name":"命运交响乐","singer":"贝多芬","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/贝多芬-命运交响乐.mp3","lrc":""},
{"name":"田园交响曲","singer":"贝多芬","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/贝多芬-田园交响曲.mp3","lrc":""},
{"name":"月光奏鸣曲","singer":"贝多芬","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/贝多芬-月光奏鸣曲.mp3","lrc":""},
{"name":"殇","singer":"杜普雷","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/杜普雷-殇.mp3","lrc":""},
{"name":"水晶音乐","singer":"宫崎骏 龙猫","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/宫崎骏 龙猫-水晶音乐.mp3","lrc":""},
{"name":"天空之城","singer":"久石让","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/久石让-天空之城.mp3","lrc":""},
{"name":"走过绿意","singer":"凯文柯恩","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/凯文柯恩-走过绿意.mp3","lrc":""},
{"name":"In Memories “A boy meets The Man”","singer":"浪客剑心","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/浪客剑心-In Memories “A boy meets The Man”.mp3","lrc":""},
{"name":"钟","singer":"李斯特","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/李斯特-钟.mp3","lrc":""},
{"name":"爱的纪念","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-爱的纪念.mp3","lrc":""},
{"name":"爱的协奏曲","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-爱的协奏曲.mp3","lrc":""},
{"name":"爱之梦","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-爱之梦.mp3","lrc":""},
{"name":"出埃及记","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-出埃及记.mp3","lrc":""},
{"name":"给母亲的信","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-给母亲的信.mp3","lrc":""},
{"name":"海边的祈祷","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-海边的祈祷.mp3","lrc":""},
{"name":"海边的星空","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-海边的星空.mp3","lrc":""},
{"name":"欢乐颂","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-欢乐颂.mp3","lrc":""},
{"name":"欢乐之歌","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-欢乐之歌.mp3","lrc":""},
{"name":"蓝色的爱","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-蓝色的爱.mp3","lrc":""},
{"name":"蓝色狂想曲","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-蓝色狂想曲.mp3","lrc":""},
{"name":"罗密欧与朱丽叶","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-罗密欧与朱丽叶.mp3","lrc":""},
{"name":"玫瑰色的人生","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-玫瑰色的人生.mp3","lrc":""},
{"name":"梦中的婚礼","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-梦中的婚礼.mp3","lrc":""},
{"name":"梦中的鸟","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-梦中的鸟.mp3","lrc":""},
{"name":"秘密的庭院","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-秘密的庭院.mp3","lrc":""},
{"name":"乒乓之恋","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-乒乓之恋.mp3","lrc":""},
{"name":"秋日私语","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-秋日私语.mp3","lrc":""},
{"name":"柔如彩虹","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-柔如彩虹.mp3","lrc":""},
{"name":"伤感乐曲","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-伤感乐曲.mp3","lrc":""},
{"name":"少女的祈祷","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-少女的祈祷.mp3","lrc":""},
{"name":"水边的阿狄丽娜","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-水边的阿狄丽娜.mp3","lrc":""},
{"name":"思乡曲","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-思乡曲.mp3","lrc":""},
{"name":"瓦妮莎的微笑","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-瓦妮莎的微笑.mp3","lrc":""},
{"name":"忘却的悲伤","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-忘却的悲伤.mp3","lrc":""},
{"name":"威尼斯之旅","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-威尼斯之旅.mp3","lrc":""},
{"name":"午后的旅行","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-午后的旅行.mp3","lrc":""},
{"name":"星空","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-星空.mp3","lrc":""},
{"name":"野花","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-野花.mp3","lrc":""},
{"name":"英雄交响曲","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-英雄交响曲.mp3","lrc":""},
{"name":"永远爱你","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-永远爱你.mp3","lrc":""},
{"name":"致爱丽丝","singer":"理查德 克莱德曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/理查德 克莱德曼-致爱丽丝.mp3","lrc":""},
{"name":"","singer":"绿钢琴 乐曲.mp3","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/绿钢琴 乐曲.mp3","lrc":""},
{"name":"克罗地亚狂想曲","singer":"马克西姆","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/马克西姆-克罗地亚狂想曲.mp3","lrc":""},
{"name":"天鹅 大提琴演奏","singer":"马友友","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/马友友-天鹅 大提琴演奏.mp3","lrc":""},
{"name":"","singer":"莫扎特 c大调小星星变奏曲.mp3","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/莫扎特 c大调小星星变奏曲.mp3","lrc":""},
{"name":"安魂曲","singer":"莫扎特","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/莫扎特-安魂曲.mp3","lrc":""},
{"name":"魔笛","singer":"莫扎特","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/莫扎特-魔笛.mp3","lrc":""},
{"name":"土耳其进行曲","singer":"莫扎特","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/莫扎特-土耳其进行曲.mp3","lrc":""},
{"name":"小步舞曲","singer":"莫扎特","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/莫扎特-小步舞曲.mp3","lrc":""},
{"name":"摇篮曲","singer":"莫扎特","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/莫扎特-摇篮曲.mp3","lrc":""},
{"name":"幽默曲","singer":"莫扎特","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/莫扎特-幽默曲.mp3","lrc":""},
{"name":"永恒的记忆","singer":"齐普利安·波隆贝斯库","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/齐普利安·波隆贝斯库-永恒的记忆.mp3","lrc":""},
{"name":"哀歌","singer":"犬夜叉","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/犬夜叉-哀歌.mp3","lrc":""},
{"name":"跨越时代的思念","singer":"犬夜叉","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/犬夜叉-跨越时代的思念.mp3","lrc":""},
{"name":"莲花","singer":"神秘园","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/神秘园-莲花.mp3","lrc":""},
{"name":"夜曲","singer":"神秘园","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/神秘园-夜曲.mp3","lrc":""},
{"name":"月亮门","singer":"神秘园","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/神秘园-月亮门.mp3","lrc":""},
{"name":"月亮门","singer":"神秘园之歌","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/神秘园之歌-月亮门.mp3","lrc":""},
{"name":"Project","singer":"神思者","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/神思者-Project.mp3","lrc":""},
{"name":"悲情城市","singer":"神思者","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/神思者-悲情城市.mp3","lrc":""},
{"name":"故宫的记忆","singer":"神思者","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/神思者-故宫的记忆.mp3","lrc":""},
{"name":"海之女神","singer":"神思者","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/神思者-海之女神.mp3","lrc":""},
{"name":"圣母颂","singer":"舒伯特","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/舒伯特-圣母颂.mp3","lrc":""},
{"name":"梦幻曲","singer":"舒曼","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/舒曼-梦幻曲.mp3","lrc":""},
{"name":"普罗旺斯的陆地和海洋","singer":"威尔第 茶花女","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/威尔第 茶花女-普罗旺斯的陆地和海洋.mp3","lrc":""},
{"name":"月光石 Rurutia","singer":"乌鸦 片尾曲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/乌鸦 片尾曲-月光石 Rurutia.mp3","lrc":""},
{"name":"飞天","singer":"喜多郎","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/喜多郎-飞天.mp3","lrc":""},
{"name":"菩提树","singer":"喜多郎","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/喜多郎-菩提树.mp3","lrc":""},
{"name":"幻想即兴曲","singer":"萧邦","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/萧邦-幻想即兴曲.mp3","lrc":""},
{"name":"森林狂想曲","singer":"徐仁修","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/徐仁修-森林狂想曲.mp3","lrc":""},
{"name":"寂静之声","singer":"姚斯婷","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/姚斯婷-寂静之声.mp3","lrc":""},
{"name":"溜冰圆舞曲","singer":"约翰 施特劳斯","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/约翰 施特劳斯-溜冰圆舞曲.mp3","lrc":""},
{"name":"闲聊波尔卡","singer":"约翰 施特劳斯","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/约翰 施特劳斯-闲聊波尔卡.mp3","lrc":""},
{"name":"蓝色多瑙河","singer":"约翰·施特劳斯","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/约翰·施特劳斯-蓝色多瑙河.mp3","lrc":""},
{"name":"维也纳森林的故事","singer":"约翰·施特劳斯","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/约翰·施特劳斯-维也纳森林的故事.mp3","lrc":""},
{"name":"杜鹃圆舞曲","singer":"约纳森","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/约纳森-杜鹃圆舞曲.mp3","lrc":""},
{"name":"故乡的原风景","singer":"宗次郎","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/空灵/宗次郎-故乡的原风景.mp3","lrc":""},


],
[
	{
		"basic":true,
		"name":"其他音乐",
		"singer":"其他",
		"img":"./img/fm1.jpg"
	},

{"name":"Only_Time","singer":"enya","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/enya-Only_Time.mp3","lrc":""},
{"name":"never say goodbye","singer":"hayleyWestenra","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/hayleyWestenra-never say goodbye.mp3","lrc":""},
{"name":"因为是女子","singer":"kiss","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/kiss-因为是女子.mp3","lrc":""},
{"name":"NachdiPhira","singer":"MeghnaMishra","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/MeghnaMishra-NachdiPhira.mp3","lrc":""},
{"name":"lonely","singer":"nana","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/nana-lonely.mp3","lrc":""},
{"name":"斯卡布罗集市","singer":"sarahBrightman","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/sarahBrightman-斯卡布罗集市.mp3","lrc":""},
{"name":"just one last dance","singer":"SarahCoonor","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/SarahCoonor-just one last dance.mp3","lrc":""},
{"name":"即使知道要见面","singer":"sara","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/sara-即使知道要见面.mp3","lrc":""},
{"name":"改变化装","singer":"WAX","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/WAX-改变化装.mp3","lrc":""},
{"name":"渴望爱情","singer":"WAX","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/WAX-渴望爱情.mp3","lrc":""},
{"name":"余情","singer":"WAX","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/WAX-余情.mp3","lrc":""},
{"name":"everytime","singer":"布兰妮","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/布兰妮-everytime.mp3","lrc":""},
{"name":"从开始到现在","singer":"冬季恋歌","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/冬季恋歌-从开始到现在.mp3","lrc":""},
{"name":"风姿花传","singer":"谷村新司","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/谷村新司-风姿花传.mp3","lrc":""},
{"name":"YesterdayOnceMore","singer":"卡朋特","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/卡朋特-YesterdayOnceMore.mp3","lrc":""},
{"name":"祈祷","singer":"蓝色生死恋","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/蓝色生死恋-祈祷.mp3","lrc":""},
{"name":"AlsoILoveYou","singer":"李秀英","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/李秀英-AlsoILoveYou.mp3","lrc":""},
{"name":"NEVERAGAIN","singer":"李秀英","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/李秀英-NEVERAGAIN.mp3","lrc":""},
{"name":"ChaCha","singer":"柳真","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/柳真-ChaCha.mp3","lrc":""},
{"name":"MyMemory","singer":"裴勇俊","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/裴勇俊-MyMemory.mp3","lrc":""},
{"name":"RAIN","singer":"朴惠京","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/朴惠京-RAIN.mp3","lrc":""},
{"name":"Gee","singer":"少女时代","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/少女时代-Gee.mp3","lrc":""},
{"name":"MrTaxi","singer":"少女时代","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/少女时代-MrTaxi.mp3","lrc":""},
{"name":"TheBoys","singer":"少女时代","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/少女时代-TheBoys.mp3","lrc":""},
{"name":"天使消逝的地方","singer":"斯维特拉娜 斯维吉科娃","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/斯维特拉娜 斯维吉科娃-天使消逝的地方.mp3","lrc":""},
{"name":"MyHeartWillGoOn","singer":"铁达尼号主题曲","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/铁达尼号主题曲-MyHeartWillGoOn.mp3","lrc":""},
{"name":"我相信","singer":"我的野蛮女友","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/我的野蛮女友-我相信.mp3","lrc":""},
{"name":"都走吧","singer":"严正花","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/严正花-都走吧.mp3","lrc":""},
{"name":"I_Cry","singer":"有里知花","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/有里知花-I_Cry.mp3","lrc":""},
{"name":"仲夏夜之梦","singer":"玉珠铉","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/玉珠铉-仲夏夜之梦.mp3","lrc":""},
{"name":"雪華","singer":"中岛美嘉","img":"./img/fm1.jpg","src":"http://music.asia.ga/OnedriveTJ/音乐视听/简选/其他/中岛美嘉-雪華.mp3","lrc":""},





]];